/*
Do not edit this file!

This file was generated by FigmaExport, any changes made
to it will be lost the next time the file is generated.

For more details see https://github.com/RedMadRobot/figma-export
*/
package ru.mobileup.template.core.theme.values

import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import ru.mobileup.template.core.R

object Icons

@Composable
fun Icons.Ic12Delete(
    contentDescription: String? = null,
    modifier: Modifier = Modifier,
    tint: Color = Color.Unspecified
) {
    Icon(
        painter = painterResource(id = R.drawable.ic_12_delete),
        contentDescription = contentDescription,
        modifier = modifier,
        tint = tint
    )
}

@Composable
fun Icons.Ic12RightChevron(
    contentDescription: String? = null,
    modifier: Modifier = Modifier,
    tint: Color = Color.Unspecified
) {
    Icon(
        painter = painterResource(id = R.drawable.ic_12_right_chevron),
        contentDescription = contentDescription,
        modifier = modifier,
        tint = tint
    )
}

@Composable
fun Icons.Ic12Reset(
    contentDescription: String? = null,
    modifier: Modifier = Modifier,
    tint: Color = Color.Unspecified
) {
    Icon(
        painter = painterResource(id = R.drawable.ic_12_reset),
        contentDescription = contentDescription,
        modifier = modifier,
        tint = tint
    )
}
