/*
Do not edit this file!

This file was generated by FigmaExport, any changes made
to it will be lost the next time the file is generated.

For more details see https://github.com/RedMadRobot/figma-export
*/
package ru.mobileup.template.core.theme.values

import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.Font
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.unit.sp
import ru.mobileup.template.core.R

object Typography {

    val bodyBoldNormal = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 16.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val bodyBoldSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 14.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 16.0.sp,
    )
    val bodyRegularNormal = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 16.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val bodyRegularSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 14.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 16.0.sp,
    )
    val buttonBoldcaps = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 12.0.sp,
        letterSpacing = 0.24.sp,
        lineHeight = 16.0.sp,
    )
    val buttonMediumNormal = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_medium)),
        fontSize = 14.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 16.0.sp,
    )
    val buttonMediumSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_medium)),
        fontSize = 12.0.sp,
        letterSpacing = 0.12.sp,
        lineHeight = 16.0.sp,
    )
    val captionBoldExtra = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 24.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 32.0.sp,
    )
    val captionBoldSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 14.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 16.0.sp,
    )
    val captionCrossPriceLarge = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 16.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val captionMediumLarge = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_medium)),
        fontSize = 18.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val captionRegularLarge = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 18.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val captionRegularNormal = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 16.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val captionRegularSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 14.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 16.0.sp,
    )
    val captionRegularUltraSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 12.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 16.0.sp,
    )
    val titleBoldLarge = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 20.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val titleBoldNormal = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 16.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val titleBoldSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 14.0.sp,
        letterSpacing = (-0.3700000047683716).sp,
        lineHeight = 16.0.sp,
    )
    val titleMediumSmall = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_medium)),
        fontSize = 14.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 16.0.sp,
    )
    val titleRegularExtra = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 24.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 32.0.sp,
    )
    val titleRegularLarge = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_regular)),
        fontSize = 20.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 24.0.sp,
    )
    val titleBoldVeryLarge = TextStyle(
        fontFamily = FontFamily(Font(R.font.robotoroman_bold)),
        fontSize = 32.0.sp,
        letterSpacing = 0.0.sp,
        lineHeight = 32.0.sp,
    )
}
